name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: a5432ce8-9ca0-4741-b827-7f90f415722f
          heroku_app_name: "crimes-rest-api"
          heroku_email: "max.rez@list.ru"
          buildpack: "https://github.com/jincod/dotnetcore-buildpack"
